#! python

from Bio import SeqIO
def get_sequences_from_file(fasta_fn):

    sequence_data_dict = {}

    for record in SeqIO.parse(fasta_fn, "fasta"):

        description = record.description.split()

        species_name = description[1] + " " + description[2]

        sequence_data_dict[species_name] = record.seq

    return(sequence_data_dict)
from Bio.Data import CodonTable
from Bio.Seq import Seq
from Bio.Alphabet import IUPAC

def translate_function(string_nucleotides):
  mito_table = CodonTable.unambiguous_dna_by_name["Vertebrate Mitochondrial"]

  aa_seq_string =""
  for i in range(0, len(string_nucleotides), 3):

      codon = string_nucleotides[i:i+3]
      if codon in mito_table.stop_codons:
            break

      aminoacid = mito_table.forward_table[codon]

      aa_seq_string += aminoacid

  return(aa_seq_string)


def get_proportion_aa(aa_seq):

            charged = ['R','K','D','E']
            polar = ['Q','N','H','S','T','Y','C','M','W']
            hydrophobic = ['A','I','L','F','V','P','G']
            c_count=0
            p_count=0
            h_count=0

            for aa in str(aa_seq):
                if aa in charged:
                    c_count += 1

                elif aa in polar:
                    p_count += 1

                elif aa in hydrophobic:
                    h_count += 1

            proportion_type = [c_count/len(aa_seq), p_count/len(aa_seq), h_count/len(aa_seq)]

            return proportion_type




cytb_seqs = get_sequences_from_file("bears_cytb.fasta")
import pandas as pd
bear_df = pd.read_csv("https://raw.githubusercontent.com/joelwebb/Python_Assignment/master/bears_data.csv")

species_list = list(bear_df.species)

for key, value in cytb_seqs.items():
  aa_seq2 =translate_function(str(value))

  proportion = get_proportion_aa(aa_seq2)

  bear_df.loc[bear_df.species==key, 'charged'] = proportion[0]

  bear_df.loc[bear_df.species==key, 'polar'] = proportion[1]

  bear_df.loc[bear_df.species==key, 'hydrophobic'] = proportion[2]


import seaborn as seas


bear_df = pd.read_csv("https://raw.githubusercontent.com/joelwebb/Python_Assignment/master/bears_data.csv")

bar_chart = seas.barplot(x = 'species', y = 'mass', data=bear_df)

bar_chart.set_xticklabels(labels = bear_df.species, rotation=30, horizontalalignment='right')
